# https://taskfile.dev

version: '3'

tasks:
  default:
    sources:
      - src/**/*.rs
      - wit/*.wit
      - Cargo.lock
      - Cargo.toml
      - Cargo-component.lock
    generates:
      - ../dist/nix.wasm
    cmds:
      - mkdir -p ../dist/
      - cargo component build --release
      - cp target/wasm32-wasip1/release/nix.wasm ../dist/nix.wasm
  clean:
    cmds:
      - rm -f ../dist/nix.wasm
      - rm -rf ./target
