# https://taskfile.dev

version: '3'

includes:
  nix:
    taskfile: ./nix/Taskfile.yml
    dir: ./nix
  wit:
    taskfile: ./wit/Taskfile.yml
    dir: ./wit
  tasks:
    taskfile: ./tasks/Taskfile.yml
    dir: ./tasks

tasks:
  default:
    cmds:
      - task: nix
      - task: gen_libs
      - task: compile
      - task: compose
  dev:
    deps:
      - default
    cmds:
      - wasmtime --dir=. ./dist/snow.wasm 
  compile:
    sources:
      - ./src/*.gr
      - ./adapters/wasi_snapshot_preview1.command.wasm
      - ./wit/*.wit
    generates:
      - ./dist/snow.gr.wasm
      - ./dist/snow.c.wasm
    cmds:
      - mkdir -p dist
      # Compile Grain component
      # grain_component <wit> <world> <adapter> <input> <output>
      - ./tasks/grain_component.sh ./wit snow ./adapters/wasi_snapshot_preview1.command.wasm  ./src/snow.gr ./dist/snow.c.wasm
  compose:
    sources:
      - ./dist/snow.c.wasm
      - ./dist/nix.wasm
    generates:
      - ./dist/snow.wasm
    cmds:
      - wac plug ./dist/snow.c.wasm --plug ./dist/nix.wasm -o ./dist/snow.wasm
  gen_libs:
    sources:
      - wit/*.wit
    generates:
      - src/libs/snow.gr
    cmds:
      # Generate Rnix Lib
      - ./bin/wit-bindgen grain wit --out-dir ./src/libs --world snow
  clean:
    cmds:
      - rm -f ./src/libs/rnix.gr
      - rm -f ./dist/
      - rm **.gr.wasm
