# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2021"]
includes = ["*.rs"]

# TODO: Configure Grain Formatter
# TODO: Configure Nix Formatter
# TODO: Configure Amber Formatter
# TODO: Configure Task File Formatter???
# TODO: Configure Toml Formatter