package snow:host@0.0.1;

interface host {
  read-file: func(path: string) -> string;
  parse-nix: func(code: string);
}

world snow {
  import host;
}

world snow-host {
  include snow;
  export run: func();
}