# https://taskfile.dev

version: '3'

tasks:
  default:
    deps: [clean]
    cmds:
      # Build
      - wit build
  publish:
    deps: 
      - default
    sources:
      - ./snow.wasm
    cmds:
      - warg publish release --name spotandjake:snow --version 0.0.6 snow.wasm
  clean:
    cmds:
      - rm -rf *.wasm
