# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: clean
      - task: copy_build
      - task: publish
  publish:
    sources:
      - ./*.wit
    generates:
      - ./snow.wasm
    cmds:
      - wit build
      # TODO: Fetch version from central location.
      - warg publish release --name spotandjake:snow --version 0.0.12 snow.wasm
  copy_buid:
    sources:
      - ../nix/wit/nix.wit
    generates:
      - ./nix.wit
    cmds:
      - cp ../nix/wit/nix.wit ./nix.wit
  clean:
    cmds:
      - rm -rf *.wasm
      - rm -f ./nix.wit
