# https://taskfile.dev

version: '3'

tasks:
  source:
    sources:
      - ../nix/wit/nix.wit
    generates:
      - ./nix.wit
    cmds:
      - rm nix.wit
      - cp ../nix/wit/nix.wit ./nix.wit
  default:
    deps: [clean]
    cmds:
      # Build
      - wit build
  publish:
    deps: 
      - default
    sources:
      - ./snow.wasm
    cmds:
      - warg publish release --name spotandjake:snow --version 0.0.12 snow.wasm
  clean:
    cmds:
      - rm -rf *.wasm
