# https://taskfile.dev

version: '3'

tasks:
  copy_buid:
    deps: [clean]
    sources:
      - ../nix/wit/nix.wit
    generates:
      - ./nix.wit
    cmds:
      - cp ../nix/wit/nix.wit ./nix.wit
  clean:
    cmds:
      - rm -rf *.wasm
      - rm -f ./nix.wit
  # TODO: Clean this up
  default:
    deps: [clean]
    cmds:
      # Build
      - wit build
  publish:
    deps: 
      - default
    sources:
      - ./snow.wasm
    cmds:
      # TODO: Fetch version from central location.
      - warg publish release --name spotandjake:snow --version 0.0.12 snow.wasm
